/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/rafi/cyclonedds/helloworld/ResultData.h
  Source: /home/rafi/cyclonedds/share/CycloneDDS/examples/helloworld/ResultData.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__HOME_RAFI_CYCLONEDDS_HELLOWORLD_RESULTDATA_H_BD8DA2DEFE503D7AA3C44A7ACBE8128F
#define DDSC__HOME_RAFI_CYCLONEDDS_HELLOWORLD_RESULTDATA_H_BD8DA2DEFE503D7AA3C44A7ACBE8128F

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct custom_trajectory_msgs_msg_ResultData
{
  double m_cost;
  bool m_feasible;
} custom_trajectory_msgs_msg_ResultData;

extern const dds_topic_descriptor_t custom_trajectory_msgs_msg_ResultData_desc;

#define custom_trajectory_msgs_msg_ResultData__alloc() \
((custom_trajectory_msgs_msg_ResultData*) dds_alloc (sizeof (custom_trajectory_msgs_msg_ResultData)));

#define custom_trajectory_msgs_msg_ResultData_free(d,o) \
dds_sample_free ((d), &custom_trajectory_msgs_msg_ResultData_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_RAFI_CYCLONEDDS_HELLOWORLD_RESULTDATA_H_BD8DA2DEFE503D7AA3C44A7ACBE8128F */
